Added toy repository for custom calculator
stevehoover/1st-CLaaS pull request #45
Opened 2020-10-28 10:30 UTC by ayush-saran

This is the customized Calculator Kernel using 1st-CLaaS.

2020-10-30 18:04 UTC, stevehoover requested changes
Looks pretty good, but please make the requested changes.

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/README.md
> +    This completes the transfer of data from the input and output side of the kernel respectively. To run the application locally, one must shift to the directory /apps/toy/build and run the command
Please rename the `/toy` directory and necessary references to `/calculator`.

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/tlv_varients/toy_flow_kernel.tlv.disabled
> +\m4_TLV_version 1d --fmtFlatSignals --bestsv --noline: tl-x.org
You can delete this file (and probably directory).

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/tlv_varients/toy_kernel.tlv.disabled
> +\m4_TLV_version 1d --fmtFlatSignals --bestsv --noline: tl-x.org
You can delete this file, too.

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/toy_kernel.sv
> +
You can delete this file, also.

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/toy_kernel.tlv
> +         $counter = $reset?0:(>>1$counter+1);
Generally, it is best to have whitespace (or parentheses) around operators, though it is fine in this case.

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/toy_kernel.tlv
> +         // Hook up inputs to outputs to implement a no-op kernel.
Replace both comment lines with `Drive results on output`.

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/toy_kernel.tlv
> +         $valid = $reset || $counter;
`$reset || ($counter != 0)` ?
This is okay in simulation, but in real operation there is an existing `$trans_valid` that you should use (if I remember correctly).

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/toy_kernel.tlv
> +         // YOUR CODE HERE
Replace with `// Calculator logic.`

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/toy_kernel.tlv
> +         $val1[31:0] = >>2$output;
`// Extract input fields from input data.`

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/toy_kernel.tlv
> +                  ? >>2$mem[31:0] : >>2$output;
This is a single-cycle calculator that can have back-to-back operations. All `>>2` should be `>>1`.

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/fpga/src/work_in_progress/toy_kernel.sv
> +
What is this file?

2020-10-30 18:04 UTC, stevehoover commented on apps/toy/host/need_to_be_reenabled/toy.c
> +/*
Please delete this directory and both files.

2020-11-02 13:43 UTC, ayush-saran commented on apps/toy/fpga/src/work_in_progress/toy_kernel.sv
> +
This file was there when we forked it. Should we remove this too?

2020-11-02 13:56 UTC, stevehoover commented
Yes, it was probably copied when you created the app as a copy of the
vector add example. Please do delete it.

Steve Hoover <https://www.linkedin.com/in/steve-hoover-a44b607/>
774-773-8333

<http://www.redwoodeda.com/>


On Mon, Nov 2, 2020 at 8:44 AM ayush-saran <notifications@github.com> wrote:

> *@ayush-saran* commented on this pull request.
> ------------------------------
>
> In apps/toy/fpga/src/work_in_progress/toy_kernel.sv
> <https://github.com/stevehoover/1st-CLaaS/pull/45#discussion_r515979324>:
>
> > @@ -0,0 +1,101 @@
> +
>
> This file was there when we forked it. Should we remove this too?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/stevehoover/1st-CLaaS/pull/45#discussion_r515979324>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACWHLEF7VKMQM2AER6OREBLSN2ZSJANCNFSM4TCEBVAQ>
> .
>

2020-11-02 14:13 UTC, ayush-saran commented on apps/toy/README.md
> +    This completes the transfer of data from the input and output side of the kernel respectively. To run the application locally, one must shift to the directory /apps/toy/build and run the command
We made all the requested changes, but when we rename "toy"to "calculator" locally, it's causing issues. Is there anywhere else we should be renaming it

2020-11-02 17:11 UTC, stevehoover approved these changes
Looks good!

2020-11-02 17:11 UTC, merged